language: node_js
dist: precise
node_js:
- 7
branches:
    only:
    - source
before_script:
- npm install -g grunt
- npm install -g grunt-site
script: grunt
after_success:
- bash ./deploy.sh
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh success $WEBHOOK_URL
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- ./send.sh failure $WEBHOOK_URL
env:
    global:
    - ENCRYPTION_LABEL: "73d8465e773a"
    - COMMIT_AUTHOR_EMAIL: "MCResourcePile@gmail.com"
